[project]
name = "python-template"
version = "0.1.0"
description = "Python template for projects"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cookiecutter>=2.6.0",
    "sphinx>=8.1.3",
    "myst-parser>=4.0.0",
    "sphinx-wagtail-theme>=6.4.0",
]
